"use client";

import Link from "next/link";
import { useState } from "react";
import { PageState, Status, percent, shortHash, useDashboard } from "@/components/regops";

const steps = ["Regulation", "Agent Impact", "Policy", "Simulation", "Human Approval", "Deployment"];

export default function ComplianceCase() {
  const state = useDashboard();
  const [step, setStep] = useState(0);
  if (!state.data) return <PageState error={state.error} retry={state.reload} />;
  const { data } = state;
  const p = data.candidate_policy;
  const replay = data.evaluation.replay;

  return <main className="page case-page">
    <header className="page-title"><div><p className="eyebrow">Case {data.case_id}</p><h1>{data.regulation.title}</h1><p>Follow a regulation from interpretation to active runtime control.</p></div><Status tone="good">{data.deployment.status}</Status></header>
    <nav className="stepper" aria-label="Compliance workflow">{steps.map((name, index) => <button key={name} onClick={() => setStep(index)} className={index === step ? "current" : index < step ? "complete" : ""} aria-current={index === step ? "step" : undefined}><span>{index < step ? "✓" : index + 1}</span><b>{name}</b></button>)}</nav>

    <section className="workflow-stage">
      <div className="stage-label"><span>Step {step + 1} of 6</span><strong>{steps[step]}</strong></div>
      {step === 0 && <div className="stage-content regulation-stage"><div className="stage-intro"><p className="eyebrow">Source regulation</p><h2>{data.regulation.title}</h2><blockquote>“{data.regulation.source_text}”</blockquote></div><div className="fact-grid"><div><span>Protected classification</span><strong>{data.regulation.requirement.data_classification}</strong></div><div><span>Governed action</span><strong>{data.regulation.requirement.governed_action}</strong></div><div><span>Allowed destination</span><strong>{data.regulation.requirement.allowed_destination}</strong></div><div><span>Required purpose</span><strong>{data.regulation.requirement.required_purpose}</strong></div></div><div className="validation-row"><Status tone="good">✓ Model Armor screened</Status><Status tone="good">✓ Gemini interpreted</Status><Status tone="good">✓ Python validated</Status></div></div>}
      {step === 1 && <div className="stage-content"><div className="stage-summary"><div><strong>{data.impact.analyzed_agent_count}</strong><span>Agents analyzed</span></div><div><strong>{data.impact.affected_agent_count}</strong><span>Agents affected</span></div><p>Source: <b>{data.enterprise_fleet.registry_source}</b></p></div><div className="impact-list">{data.impact.agents.map(agent => <article key={agent.agent_id} className={agent.status === "AFFECTED" ? "impact-card affected" : "impact-card"}><div><h3>{agent.agent_name}</h3><code>{agent.agent_id} · v{agent.agent_version}</code></div><Status tone={agent.status === "AFFECTED" ? "risk" : agent.status === "NEEDS_REVIEW" ? "warn" : "neutral"}>{agent.status}</Status><p>{agent.reasons[0]}</p>{agent.capability_paths.map((path, i) => <div className="capability-path" key={`${path.tool_name}-${i}`}><span>{path.data_classification}</span><i>→</i><span>{agent.agent_name}</span><i>→</i><span>{path.tool_name}</span><i>→</i><span>{path.destination_type}</span></div>)}</article>)}</div></div>}
      {step === 2 && <div className="stage-content policy-stage"><div className="policy-header"><div><p className="eyebrow">Enforceable control</p><h2>{p.policy_id} <small>v{p.version}</small></h2></div><Status tone="good">{p.runtime_status}</Status></div><div className="policy-statement"><span>PROTECT</span><strong>{p.protected_classification}</strong><span>WHEN</span><strong>{p.governed_action}</strong><span>ALLOW ONLY WHEN</span><strong>destination = {p.allowed_destination}<br/>purpose = {p.required_purpose}</strong><span>OTHERWISE</span><strong className="deny-text">DENY</strong></div><p className="artifact-flow">AI generated <b>→</b> Python validated</p><details><summary>Technical artifact details</summary><code>Fingerprint: {p.fingerprint}</code></details></div>}
      {step === 3 && <div className="stage-content"><div className="score-grid">{[["Compliance", data.evaluation.compliance, true],["Utility", data.evaluation.utility, true],["Adversarial", data.evaluation.adversarial, true],["Critical violations", data.evaluation.critical_violations, false]].map(([label, pair, asPercent]) => { const score = pair as {baseline:number;candidate:number}; return <div key={label as string}><span>{label as string}</span><p><del>{asPercent ? percent(score.baseline) : score.baseline}</del><i>→</i><strong>{asPercent ? percent(score.candidate) : score.candidate}</strong></p><small>Baseline → candidate</small></div>})}</div><div className="replay-summary"><div><span>Blast radius</span><strong>{percent(data.evaluation.blast_radius)}</strong></div>{[["Total",replay.total_actions],["Unchanged",replay.unchanged],["Newly denied",replay.newly_denied],["Newly allowed",replay.newly_allowed]].map(([label,value]) => <div key={label}><span>{label}</span><strong>{value}</strong></div>)}</div><details className="test-details"><summary>View representative compliance tests ({data.tests.total_count} total)</summary>{data.tests.representative_cases.map(test => <article key={test.test_id}><Status tone={test.expected_decision === "DENY" ? "risk" : "good"}>{test.expected_decision}</Status><div><strong>{test.scenario}</strong><small>{test.category} · {test.agent_id} → {test.tool_name}</small></div></article>)}</details></div>}
      {step === 4 && <div className="stage-content approval-stage"><div className="approval-mark">✓</div><h2>Approved for deployment</h2><p>The exact policy evaluated in simulation is the same artifact approved by the reviewer.</p><dl><div><dt>Reviewer</dt><dd>{data.review.reviewer.display_name}</dd></div><div><dt>Role</dt><dd>{data.review.reviewer.role}</dd></div><div><dt>Decision</dt><dd className="positive">{data.review.decision}</dd></div><div><dt>Reviewed</dt><dd>{new Date(data.review.reviewed_at).toLocaleString()}</dd></div><div><dt>Simulation</dt><dd>{data.evaluation.status}</dd></div><div><dt>Artifact match</dt><dd>EXACT MATCH · {shortHash(data.review.policy_fingerprint)}</dd></div></dl></div>}
      {step === 5 && <div className="stage-content deployment-stage"><span className="active-badge">ACTIVE</span><h2>{p.policy_id} <small>version {data.deployment.active_version}</small></h2><p>The approved control is now enforced by the deterministic runtime gateway.</p><dl><div><dt>Environment</dt><dd>{data.deployment.environment}</dd></div><div><dt>Activated</dt><dd>{new Date(data.deployment.activated_at).toLocaleString()}</dd></div><div><dt>Deployment ID</dt><dd>{data.deployment.deployment_id}</dd></div></dl><Link href="/runtime" className="primary-button">Open runtime monitor →</Link></div>}
    </section>
    <div className="step-controls"><button className="secondary-button" disabled={step === 0} onClick={() => setStep(step - 1)}>← Back</button><span>{step + 1} / {steps.length}</span><button className="primary-button" disabled={step === steps.length - 1} onClick={() => setStep(step + 1)}>Next →</button></div>
  </main>;
}
